### ISSUE TITLE
Consider populating User.roles from token

### ISSUE THREAD

**Issue by jbolanosg** [wundergraph/wundergraph#1084]
I do not know that problem exist when keycloak jwt is parsed in wundergraph....The array roles is not populate..role attribute comes with null value....For fix this situation i use this hook:
```
authentication: {
     mutatingPostAuthentication: async ({ user }) => {
              console.log("===Autenticacion===")
              console.log(user.roles)
              if  (user.roles === null) {
                if (user.accessToken) {
                    console.log(user.accessToken.roles)
                    user.roles = Object.values(user.accessToken.roles)

                }
              }
              console.log(user.roles)

              return {
                user,
                status: 'ok',
              };
            },
          },
```
With this senteces i populate the property roles in user object:
user.roles = Object.values(user.accessToken.roles)
I will want that wundergraph teams will review because the property roles is not populate if in jwt in delivered for keycloak comes with attribute roles like as arrays of strings?

I suggest using the same pattern used by Hasura configuring special claims like "x-hasura-allowed-roles" in wundergraph could be "x-wundergraph-allowed-roles". https://hasura.io/docs/latest/auth/authentication/jwt/

**Comment by scshiv29-dev** [comment]
hey @Slickstef11  could you please give me a starting point for this so i can solve this issue ?

**Comment by rishi-raj-jain** [comment]
/attempt 1084

@jbolanosg Where do you do that fix? Can you share that?

**Comment by jbolanosg** [comment]
> /attempt 1084
> 
> @jbolanosg Where do you do that fix? Can you share that?

In hook mutatingPostAuthentication, In the description of the Issue is the code that i used.

**Comment by ShaneMaglangit** [comment]
Will start investigating and coming up with possible solution

/attempt #1084

**Comment by Pagebakers** [comment]
@ShaneMaglangit 

Thanks for picking this up. For reference:

Ideally we'd auto populate the roles from the keycloak token automatically. 

Investigate why WunderGraph doesn't pick up the roles from keycloak
Pass the roles into the user claims
Make sure the roles are supported (configured in the authorize config, the default is 'admin' and 'user')

**Comment by ShaneMaglangit** [comment]
@Pagebakers how should we handle instances we're the roles extracted from the claims isn't supported? Do we filter it out or throw out an Error?

**Comment by ShaneMaglangit** [comment]
@Pagebakers @jbolanosg Can you help clarify if we just want to extract the `roles` field off the access token or do we want to extract the `realm roles`.

I am not sure if the provided snippet above did actually work as a bandaid for this. Looking at the raw token passed, it looks like it shouldn't? Mainly because we don't actually have a role field under `user.accessToken`.

This is not because "we are not picking up the roles from keycloak", but rather keycloak structures its roles differently (realm roles, client roles).

```json
{
  "exp": 1695488590,
  "iat": 1695488290,
  "auth_time": 1695487426,
  "jti": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "iss": "http://localhost:8080/realms/demo",
  "aud": "account",
  "sub": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "typ": "Bearer",
  "azp": "demo-client",
  "session_state": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "acr": "0",
  "realm_access": {
    "roles": [
      "offline_access",
      "uma_authorization",
      "default-roles-demo"
    ]
  },
  "resource_access": {
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "openid profile email",
  "sid": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "email_verified": false,
  "name": "John Doe",
  "preferred_username": "johndoe",
  "given_name": "John",
  "family_name": "Doe",
  "email": "johndoe@gmail.com"
}
```

**Comment by ShaneMaglangit** [comment]
Hmm, this seems beyond my capacity. Mainly since I'm quite unsure how to differentiate keycloak over other providers. Passing on this one for now, feel free to take this on my stead :ok_man:

**Comment by ShaneMaglangit** [comment]
Hi @Pagebakers @jbolanosg, I seem to have found out how to resolve this issue. Turns out, we don't need to add any additional changes at all, except perhaps a documentation update. The issue is with keycloak and how it structures the UserInfo it returns.

Here are the steps required for the `role` field to get populated without the hook workaround.

1. Go to the keycloak admin console, login and make sure that you're in the correct realm:
![image](https://github.com/wundergraph/wundergraph/assets/53674742/2febcaae-d3de-4bc0-a210-b0c8202c14f9)
2. Go to **Client Scopes** > **roles**.
3. Tick `Include in token scope`.
4. On the same page, switch to the **Mappers** tab.
5. Go to **realm roles** or **client roles**, depending on which one would you like to use for the role field. fwiw, I'm not yet sure what's the distinction between the two.
 - Tick the switches for **Add to ID Token**, **Add to Access Token**, **Add to UserInfo**
 - Set **Token Claim Name** to `roles`.

Apply all the changes and the roles should now be populated. Here's a demo of the result using the keycloak example, where you can see that the roles is now populated.
![image](https://github.com/wundergraph/wundergraph/assets/53674742/bfcb0287-0557-4cb4-8a5e-65ae14cfbbfa)

I'll be creating a new PR to update the documentation and hopefully claim the bounty :smile:

**Comment by Pagebakers** [comment]
Looks like this solution will work, we are reviewing it +1
