### ISSUE TITLE
Graphql field names in camelCase

### ISSUE THREAD

**Issue by shiftlabs1** [wundergraph/wundergraph#1094]
## Problem
To enable consistency with respect to types, is it possible to include a config setting that aliases the generated graphql fields as camelCase to enable type consistency in Js and typescript apps for example

We usually generate typescript types as camelCase but postgres table names and columns are snake cased and the generated graphql schema follows the same pattern . 
## Suggested solution
Provide a Config flag to enable generated fields in camelCase so that it is Opt in only . This can be an option passed to introspect.graphql or any of the types. e.g 
```
const db = introspect.postgresql({
	apiNamespace: 'db',
	databaseURL: new EnvironmentVariable('DATABASE_URL'),
        namesCase:'camel' //or snake or pascal
})

```
The generated schema may just be aliased like below 

```
# This file is auto generated.
# Remove/modify this header if you want to customize the operation.
mutation db_createOneusers_mutation($data: db_usersCreateInput!) {
  db_createUser(data: $data) {
    id
    firstName:first_name
    lastName:last_name
    email
    isActive: is_active
    idDocumentNumber: id_document_number
    gender
    createdAt: created_at
    updatedAt:updated_at
  }
}
```
## Alternatives

Hasura Offers this functionality via Config , even for the generated Operations / resolvers

**Comment by kaf-lamed-beyt** [comment]
@Slickstef11, I'd love to work on this but I'm new to this repository, can you please direct me to the file or folder that I need to focus on?

**Comment by switchupcb** [comment]
I will solve this issue for a [direct one-time sponsorship](https://github.com/sponsors/switchupcb?frequency=one-time). Read the details in this issue for more information.

@Slickstef11 must tell me the following information:
- Specify the  [naming case conventions](https://en.wikipedia.org/wiki/Naming_convention_(programming)) you wish to support in the configuration.
- Share a URL that links to the line of code where the WunderGraph Server `introspect` command configuration is parsed to a respective configuration object (e.g., `introspect` struct).
- Share a URL that links to the line of code where the WunderGraph Server GraphQL `types`, `resolvers`, and `mutations` are generated [in the code; not the GraphQL file location] when a user calls `introspect` on the WunderGraph Server.

_Do not sponsor me until you have provided this information._

# Issue Modification

@shiftlabs1 must modify or assert that implementing this issue is possible without modification.

**Disclaimer of Modification.** A user cannot "alias" a GraphQL type because it would either:
- involve indirection (where a type `X_Y` resolver resolves to a type `xY` resolver).
- require the resolver to modify the actual client's GraphQL query (by replacing type `X_Y` with type `xY`) which is **NOT** PERFORMANT, thus not recommended.

_If this assertion is incorrect, please let me know._

**Proposed Modification.** The user specifies which naming case convention a Data Layer API _(e.g., PostgreSQL database, DynamoDB, REST API, GraphQL API)_ uses. The WunderGraph Server will **rename** introspected Data Layer API types, resolvers, and mutations to adhere to the specified naming case convention (in an `introspect` configuration).

**Additional Comments.** You have not specified how the original naming case convention of the Data Layer API is determined. There is no guarantee that incoming types from those layers adheres to a given naming convention, since naming conventions are a programming standard, but not required.

Furthermore, renaming a type requires that you understand its convention. So we must create a **case detection** algorithm that determines how words are separated in `types`, `resolvers`, and `mutations` declaration names.

# Conditions

I will create a pull request that implements this feature upon sponsorship with the following conditions.
- Pseudocode Implementation of GraphQL type renaming: $100
- Pseudocode Implementation of GraphQL resolver renaming: $100
- Pseudocode Implementation of GraphQL mutation renaming: $100
- Direct Implementation of Naming Case Detection of Data Layer API (fallback using regex groups specified by user): $100.
- Direct Implementation of Naming Case Detection of Data Layer API: $65 per case (e.g., camel, pascal, snake).
- Direct Implementation of Naming Convention Convention Rename Functionality: $65 per case (e.g., camel, pascal, snake).

## Condition Description

The pseudocode implementation includes a pull request with a modified WunderGraph codebase demonstrating how the feature will be implemented for the type, resolver, or mutation.

The direct implementation of a naming case detection algorithm for Data Layer API types includes an implementation of functionality that lets the user determine how words are separated in `type`, `resolver`, and `mutation` declaration names. This condition is required to implement a full implementation of this feature.

The direct implementation of a naming case detection algorithm for Data Layer API types includes an implementation of functionality that detects the case of the type, resolver, or mutation that will be renamed.

The direct implementation of naming conventions rename functionality includes an implementation of the functionality that renames the WunderGraph Server GraphQL types, resolvers, or mutations.

Opting for every condition results in an implementation that lets the Frontend Client use a renamed - but not aliased - type, resolver, or mutation in their GraphQL queries to the WunderGraph server.

_Reminder: Do not sponsor me until you have provided the information specified above._

**Comment by RayHughes** [comment]
@shiftlabs1 We solved this for Postgres by using Prisma introspection. Prisma introspection allows mapping columns to different names. You can use this package to apply the mappings automatically. https://github.com/iiian/prisma-case-format


```
# Generate / Update Prisma Schema
yarn prisma db pull

# Convert Mappings to camelCase (from snake_case)
yarn prisma-case-format
```

**Comment by ShaikhZayan** [comment]
> @Slickstef11, I'd love to work on this but I'm new to this repository, can you please direct me to the file or folder that I need to focus on?

True Please Provide The Following File Or Folder 👍

**Comment by Rutik7066** [comment]
Hi i would like to work on this issue can anyone assign this to me
