### ISSUE TITLE
[Issue]: TypeScript error in Nuxt example

### ISSUE THREAD

**Issue by lewebsimple** [wundergraph/wundergraph#1115]
### Description

In a freshly installed instance of the Nuxt example, there is a TypeScript error in `plugins/vue-query.ts`:
```
Type 'Operations' does not satisfy the constraint 'OperationsDefinition<OperationDefinition, OperationDefinition, OperationDefinition, string, S3ProviderDefinition, string, string>'.
  Type 'LiveQueries' is not assignable to type 'string'.ts(2344)
```

The project still works, but it breaks the build with strict typechecking.

Any idea what is causing this ?

### Reproduction

```
pnpm dlx create-wundergraph-app my-project --example nuxt
cd my-project
pnpm install
```
Open `plugins/vue-query.ts` in VSCode and see the error at line 31.

**Comment by fiam** [comment]
@lewebsimple This seems to be working fine here. I can't see any errors after I ran the commands you provided followed by `pnpm run build:wundergraph`. We did change `Operations` recently, but it should be entirely handled by the code generation and it should not require any code changes. Could you please let us know how are you running code generation in your example? Thanks!

**Comment by fiam** [comment]
@lewebsimple @andrechateau Thanks for the additional information. This turned out to be a problem with our vue-query package not being correctly set up for releases.

We made some incompatible changes to the internal and our vue-query package was not updated, causing it to expect the old internal API. That's also why I couldn't reproduce it in our monorepo.

The PR I've just opened should fix the problem.
