### ISSUE TITLE
[Issue]: Decimal / Numeric Postgres fields return null value in operations

### ISSUE THREAD

**Issue by RayHughes** [wundergraph/wundergraph#1166]
### Description

When attempting to access the value of a numeric (decimal) field with Prisma Data store / Postgres, the field always returns null in all operation types. When running in debug mode, the field value is properly logged to the console but continues to fail to make it into the outputted result.

In Postgres, `numeric` and `decimal` are the same field type. Prisma recognizes both field types as `decimal`

### GraphQL Query / Result

<img width="1463" alt="query" src="https://github.com/wundergraph/wundergraph/assets/4381883/6cf5f728-d2c2-4840-8d22-541c4781190a">

### Reproduction

Below is a copy of my schema with other fields hidden. All other field types on the records work perfectly. I have tried this with multiple tables and have the same result

### Prisma Config (prisma.schema)

```
model UserPick {
  grade        UserPickGrade? @map("grade")
  gradedValue  Decimal?       @map("graded_value") @sharpDb.Decimal(10, 2)
  @@map("user_pick")
}

enum UserPickGrade {
  Loss
  Push
  Cashed
  Win

  @@map("user_pick_grade")
}
```

### Postgres Field Config

```sql
    graded_value numeric(10,2),

```

### Work Around

I am able to work around this issue by changing the field types to Float in the `schema.prisma` but this is less than idea as there is a risk of losing precision and they are overwritten when regenerating the prisma schema

### System Info
- `Node` v20.5.0
- `Yarn` 1.22.19
- `@wundergraph/sdk` 0.171.0

**Comment by anothermh** [comment]
I am experiencing the same issue. The logs report that the query successfully fetched the value:

```
database.Source.Execute.Succeed request="{"query":"{getUser: findFirstuser(where: {key: {equals: \"123\"}}){key numeric_value}}","variables":{}}" response="{"data":{"getUser":{"key"":"123","numeric_value":"65.74186027"}}}"
```

But the response body received by the client has `null` instead of the number:

```json
{
    "data": {
        "getUser": {
            "key": "123",
            "numeric_value": null
        }
    }
}
```

It looks like it is related to this:

https://github.com/wundergraph/wundergraph/blob/8b2af9e0c1041655b876b3ce1266e4680cad30b7/packages/sdk/src/db/introspection.ts#L400-L413

(or more probably related to `ScalarTypeDefinition` in general)

At a glance I can't make sense of what that code is doing. It looks like it's saying if it's either a float or an integer to return null which doesn't seem right.

@StarpTech This was from https://github.com/wundergraph/wundergraph/commit/737bc30682068a1f8af9c7e75ec6e88dbab284c2 so it's not possible to dig further into history on it. Are you able to look at this?

**Comment by Pagebakers** [comment]
Could you share the generated graphql schema for the getUser query? you can find it in `.wundergraph/generated/wundergraph.schema.graphql`

**Comment by Pagebakers** [comment]
Could you try if the following works?

```ts
introspection.postgres({
// config
  replaceCustomScalarTypeFields: [
    {
      entityName: 'Decimal',
      fieldName: 'numeric_value',
      responseTypeReplacement: 'String', // or try `Float`
    },
  ])
```
