### ISSUE TITLE
Improvement request: Ability to configure the WG client at runtime

### ISSUE THREAD

**Issue by Xymmer** [wundergraph/wundergraph#1195]
## Problem

We can't configure the WG client at runtime. @wundergraph/sdk: 0.174.0

## Suggested solution

None

## Alternatives

So far, the workaround is to define the url at build time, and then it's hardcoded in the generated WG client code.  This is obviously not viable.

## Additional context

A major use case example of runtime configuration is the need to configure the URL of the BFF backend, in the frontend app using the WG generated client when running it in a given environment.

**Comment by hackergil** [comment]
@Pagebakers yes, that is correct

**Comment by Pagebakers** [comment]
Our recommended approach would be to initiate a new client with the updated baseURL.
Instead of using the generated `client` use `createClient` to initialize it with a custom baseURL.

It would be useful to know a bit more details about the use-case, maybe we with code example how you are planning to use this.

**Comment by Xymmer** [comment]
closing as we have a solution
