### ISSUE TITLE
wunderctl up client generation different from wunderctl generate

### ISSUE THREAD

**Issue by curtismj1** [wundergraph/wundergraph#275]
### Bug description

Hello wundergraph team,

I have created a nextjs project using `wunderctl init --template nextjs-postgres-starter` and installed all dependencies.

Inside the project, I have created a card model in `schema.prisma`

```
model card {
  id          Int    @id @default(autoincrement())
  iconUrl     String
  description String
}
```

as well as a corresponding "select all" style query inside `operations/findCards.graphql`

```
{
  db_findManycard {
    id         
    description 
    iconUrl   
  }
}
```

When I run `wunderctl generate`, it is able to create the client as expected.
However, when I run `wunderctl up`, I get the following error message:

`Error parsing operation findCards: Cannot query field "db_findManycard" on type "Query". Did you mean "db_findManyuser"?`

### How to reproduce

1. [Clone](https://github.com/curtismj1/wundergraph-bug)
2. Run `wunderctl generate` followed by `git diff HEAD~1`. Observe proper client generation
3. Run `wunderctl up --debug`. Observe generated client undone by `wunderctl generate`

### Expected behavior

Expect `wunderctl up` to be able to add hot reloading with same output as `wunderctl generate`.

### Environment & setup

- OS: Mac OS
- Go version: go1.19 darwin/amd64
- Database: Postgresql
- Node.js version: 17.9.1
- Yarn version: 1.22.19

### WunderCtl Version

```
0.97.0
```

**Comment by Slickstef11** [comment]
Thank you for reporting. We will be taking a closer look at this!

**Comment by kaleem68** [comment]
Hi, thanks for reporting the issue.

It looks like the issue is when you create the `card` it does not generate the queries 

if you want to make sure when you modify `schema.prisma` and it detects and generates queries.
 
Here are simple steps you can try using our latest `create-wundergraph-app` command
 
1. Use `create-wundergraph-app` command to bootstrap the prisma example
      * `npx create-wundergraph-app my-project -E nextjs-postgres-prisma`
      *  `cd my-project`
      * `npm i && npm start`
      
2. change `schema.prisma`
```
  model card {
    id          Int    @id @default(autoincrement())
    iconUrl     String
    description String
  }
```
    
3. run migrate command `npm run migrate add card`
4. remove cache from `.generated/cache`
5) `wunderctl generate`

6) Now if write the query inside `operations/findCards.graphql` it should detect
```
{
  db_findManycard {
    id         
    description 
    iconUrl   
  }
}
```
7) Inside `pages/index.tsx` type the query with latest syntax

```
	const cards = useQuery({
		operationName:"findCards"
	})

```
8) `npm start`

Does this help with your question?

**Comment by jensneuse** [comment]
Please re-open if it's still an issue.
