### ISSUE TITLE
Allow configuration of application deployment name

### ISSUE THREAD

**Issue by greemo** [wundergraph/wundergraph#4]
## Problem

At the moment the deployment name is always "main". I want to be able to configure that.

## Suggested solution

Add 'deployment' field to ApplicationConfig and Application, and use it in resolveConfig() instead of the hard-coded 'main'.

then a user could configure the deployment within configureWunderGraphApplication()

## Alternatives

Possibly allow overriding via an environment variable.

## Additional context

https://github.com/wundergraph/wundergraph/blob/97b29f2e3f487f568f10beb7a5c9327e35b61a63/packages/sdk/src/configure/index.ts#L303

https://github.com/wundergraph/wundergraph/blob/97b29f2e3f487f568f10beb7a5c9327e35b61a63/packages/sdk/src/definition/index.ts#L53

**Comment by jensneuse** [comment]
You're right that this should be configurable. I think, a good place could be the Application object: https://github.com/wundergraph/wundergraph/blob/a41ffc5282396f829668b59bb548526eff941085/examples/simple/.wundergraph/wundergraph.config.ts#L73

We could add a properly like "environment" that defaults to the currently checked out branch, if not set. Otherwise, it could be overwritten via string. But I'm not yet 100% sure. Need to discuss within the team. What's your opinion on this?

**Comment by greemo** [comment]
Yeah, adding it to the ApplicationConfig that is used to construct the Application feels like a natural place for it.

I think defaulting to branch may make deployment a bit tricky, as it affects the url.

I'd feel more comfortable with default to 'main' as it is, but can be overwritten by the applicationconfig.

It may make sense for the go server+hook server to consider an environment variable as well.
